pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Taneeshq2002/Jenkins-projects.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh '/opt/maven/bin/mvn clean install'
            }
        }
    }
}
